spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: local
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    listener:
      ack-mode: manual
    consumer:
      group-id: product-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      sasl:
        login:
          refresh:
            buffer:
              seconds: 300
            min:
              period:
                seconds: 60
            window:
              jitter: 0.05
              factor: 0.8
  profiles:
    active: local
  main:
    banner-mode: console
logging:
  level:
    org.springframework: INFO