spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service?currentSchema=local
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
topics:
   product-upsert: inventory.product.upsert.v1
   product-delete: inventory.product.delete.v1
   product-upsert-fail: inventory.product.upsert.v1.fail
   product-upsert-retry-fail: inventory.product.upsert.v1.retry-fail
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui