spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-management-system?currentSchema=local
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092