name: Build and Test

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build and Test with Testcontainers
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.2-dind
        options: --privileged --dns 8.8.8.8
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker host for Testcontainers
        run: echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create Maven Settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << 'EOF'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                    https://maven.apache.org/xsd/settings-1.0.0.xsd">
          
            <mirrors>
              <mirror>
                <id>central-mirror</id>
                <name>Maven Central Mirror</name>
                <url>https://repo1.maven.org/maven2</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>
          EOF

      - name: Build & Test with Maven
        run: mvn clean verify -Dtestcontainers.reuse.enable=false